name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Windows ランナーを指定

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Python環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 必要に応じてPythonのバージョンを指定

      # 必要な依存関係をインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas

      # specファイルを使用してEXEをビルド
      - name: Build EXE using spec file
        run: |
          pyinstaller shift_maker.spec

      # アーティファクトをアップロード
      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: shift_maker
          path: dist/shift_maker.exe  # distディレクトリに生成されたEXEファイルをアップロード