name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Windowsランナーを指定

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 必要に応じてPythonのバージョンを指定

      - name: Install PyInstaller
        run: |
          pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --name=app-name main.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-name
          path: dist/app-name.exe  # distディレクトリに出力されたexeファイルをアップロード